version: '3.1'

services:
  rrcs-db-test:
    image: postgres:15.2-bullseye
    restart: always
    environment:
      POSTGRES_DB: 'rrcs_db'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'rrcs_user'
      # You can use whatever password you like
      POSTGRES_PASSWORD: 'password'
      # Password for root access
      #MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5433:5433'
    expose:
      # Opens port 3306 on the container
      - '5433'
    command:
      - -p 5433
